[package]
edition.workspace = true
name = "pebbles-game-io"
version = "0.1.0"

[dependencies]
gstd.workspace = true
gmeta.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true
